[package]
<<<<<<<< HEAD:r-services/@tests/data_dusk_test/Cargo.toml
name = "data_dusk_test"
========
name = "cache_glow_test"
>>>>>>>> origin/master:r-services/@tests/cache_glow_test/Cargo.toml
version = "0.1.0"
edition = "2024"

[dependencies]
