version: "3"

services:
  database:
    image: postgres:latest
    container_name: arenaDb
    ports:
      - 13421:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: felDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: