[package]
name = "repositories_suite"
version = "0.1.0"
edition = "2024"

[dependencies]
persistence = {path = "../../pkg/persistence"}
application = {path = "../../pkg/application"}
rand = "0.9.2"
tempfile = "3.23.0"
tokio = { version = "1.28.2", features = ["full"] }
