[[class]]
id = "com.base.classes.warrior"
trees = [
    "com.base.classes.warrior.fury",
    "com.base.classes.warrior.masteries",
    "com.base.classes.warrior.warCries"
]

[[class]]
id = "com.base.classes.rogue"
trees = [
    "com.base.classes.rogue.javelinAndSpear",
    "com.base.classes.rogue.bows",
    "com.base.classes.rogue.passives"
]

[[class]]
id = "com.base.classes.mage"
trees = [
    "com.base.classes.mage.cold",
    "com.base.classes.mage.fire",
    "com.base.classes.mage.lightning"
]

[[talentTree]]
id = "com.base.classes.warrior.masteries"
class = "com.base.classes.warrior"

[[talentTree]]
id = "com.base.classes.warrior.fury"
class = "com.base.classes.warrior"

[[talentTree]]
id = "com.base.classes.warrior.warCries"
class = "com.base.classes.warrior"

[[talentTree]]
id = "com.base.classes.rogue.javelinAndSpear"
class = "com.base.classes.rogue"

[[talentTree]]
id = "com.base.classes.rogue.bows"
class = "com.base.classes.rogue"

[[talentTree]]
id = "com.base.classes.rogue.passives"
class = "com.base.classes.rogue"

[[talentTree]]
id = "com.base.classes.mage.cold"
class = "com.base.classes.mage"

[[talentTree]]
id = "com.base.classes.mage.fire"
class = "com.base.classes.mage"

[[talentTree]]
id = "com.base.classes.mage.lightning"
class = "com.base.classes.mage"

[[talent]]
id = "com.base.classes.axeMasteries"
tree = "com.base.classes.warrior.masteries"
row = 1
col = 1
maxRank = 10
requiredLevel = 1
requiredTalents = []

# --------- Rank 1 -----------
[[talent.rank]]
rank = 1

    [[talent.rank.value]]
    property = "com.base.properties.axeEnhancedDamage"
    value = 50.0

    [[talent.rank.value]]
    property = "com.base.properties.axeAttackRating"
    value = 100.0

# --------- Rank 2..10 (formula) -----------

[[talent.rank]]
rankFrom = 2
rankTo = 10

    [[talent.rank.value]]
    property = "com.base.properties.axeEnhancedDamage"
    formula = "50 + (rank-1)*10"

    [[talent.rank.value]]
    property = "com.base.properties.axeAttackRating"
    formula = "100 + (rank-1)*15"