[[combatAction]]
id = "com.base.combatActions.onCasting"

[[combatAction]]
id = "com.base.combatActions.onStriking"

[[combatAction]]
id = "com.base.combatActions.onAttack"

[[combatAction]]
id = "com.base.combatActions.onKill"

[[combatAction]]
id = "com.base.combatActions.whenStruck"