[[property]]
id = "com.base.properties.defense"
type = "int32"

[[property]]
id = "com.base.properties.twoHanded"
type = "boolean"

[[property]]
id = "com.base.properties.twoHandedMinimumDamage"
type = "float"

[[property]]
id = "com.base.properties.twoHandedMaximumDamage"
type = "float"

[[property]]
id = "com.base.properties.oneHandedMinimumDamage"
type = "float"

[[property]]
id = "com.base.properties.oneHandedMaximumDamage"
type = "float"

[[property]]
id = "com.base.properties.attackSpeed"
type = "int32"

[[property]]
id = "com.base.properties.requiredLevel"
type = "int32"

[[property]]
id = "com.base.properties.attackRating"
type = "int32"

[[property]]
id = "com.base.properties.additionalStrength"
type = "int32"

[[property]]
id = "com.base.properties.additionalAgility"
type = "int32"

[[property]]
id = "com.base.properties.additionalIntelligence"
type = "int32"

[[property]]
id = "com.base.properties.enhancedDamage"
type = "int32"

[[property]]
id = "com.base.properties.enhancedDefense"
type = "int32"

[[property]]
id = "com.base.properties.increaseChanceOfBlocking"
type = "int32"

[[property]]
id = "com.base.properties.lifeSteal"
type = "float"

[[property]]
id = "com.base.properties.manaSteal"
type = "float"

[[property]]
id = "com.base.properties.damageReduced"
type = "float"

[[property]]
id = "com.base.properties.fireResistance"
type = "int32"

[[property]]
id = "com.base.properties.coldResistance"
type = "int32"

[[property]]
id = "com.base.properties.lightningResistance"
type = "int32"

[[property]]
id = "com.base.properties.poisonResistance"
type = "int32"

[[property]]
id = "com.base.properties.fireAbsorb"
type = "int32"

[[property]]
id = "com.base.properties.coldAbsorb"
type = "int32"

[[property]]
id = "com.base.properties.lightningAbsorb"
type = "int32"

[[property]]
id = "com.base.properties.poisonAbsorb"
type = "int32"

[[property]]
id = "com.base.properties.fireAbsorbPercent"
type = "int32"

[[property]]
id = "com.base.properties.coldAbsorbPercent"
type = "int32"

[[property]]
id = "com.base.properties.lightningAbsorbPercent"
type = "int32"

[[property]]
id = "com.base.properties.poisonAbsorbPercent"
type = "int32"

[[property]]
id = "com.base.properties.attackerTakesDamage"
type = "int32"

[[property]]
id = "com.base.properties.replenishLife"
type = "int32"

[[property]]
id = "com.base.properties.lightRadius"
type = "int32"

[[property]]
id = "com.base.properties.increaseAttackSpeed"
type = "int32"

[[property]]
id = "com.base.properties.fasterRunWalk"
type = "int32"

[[property]]
id = "com.base.properties.fasterCastRate"
type = "int32"

[[property]]
id = "com.base.properties.bonusToAttackRating"
type = "float"

[[property]]
id = "com.base.properties.chanceToOpenWounds"
type = "float"

[[property]]
id = "com.base.properties.chanceToCrushingBlow"
type = "float"

[[property]]
id = "com.base.properties.deadlyStrike"
type = "float"

[[property]]
id = "com.base.properties.criticalStrike"
type = "float"

[[property]]
id = "com.base.properties.pierceChance"
type = "float"

[[property]]
id = "com.base.properties.fireSkillDamage"
type = "float"

[[property]]
id = "com.base.properties.coldSkillDamage"
type = "float"

[[property]]
id = "com.base.properties.lightningSkillDamage"
type = "float"

[[property]]
id = "com.base.properties.poisonSkillDamage"
type = "float"

[[property]]
id = "com.base.properties.fireResistencePierce"
type = "float"

[[property]]
id = "com.base.properties.coldResistencePierce"
type = "float"

[[property]]
id = "com.base.properties.lightingResistencePierce"
type = "float"

[[property]]
id = "com.base.properties.poisonResistencePierce"
type = "float"

[[property]]
id = "com.base.properties.physicalResistencePierce"
type = "float"

[[property]]
id = "com.base.properties.lifeAfterEachKill"
type = "int32"

[[property]]
id = "com.base.properties.manaAfterEachKill"
type = "int32"

[[property]]
id = "com.base.properties.lifeAfterEachHit"
type = "int32"

[[property]]
id = "com.base.properties.manaAfterEachHit"
type = "int32"

[[property]]
id = "com.base.properties.useEvent"
type = "com.base.types.useEvent"



[[property]]
id = "com.base.properties.axeEnhancedDamage"
type = "float"

[[property]]
id = "com.base.properties.axeAttackRating"
type = "float"



[[property]]
id = "com.base.properties.minimumSockets"
type = "int32"

[[property]]
id = "com.base.properties.maximumSockets"
type = "int32"

[[property]]
id = "com.base.properties.weaponAttackSpeed"
type = "int32"

[[property]]
id = "com.base.properties.durability"
type = "int32"

[[property]]
id = "com.base.properties.minimumDefense"
type = "int32"

[[property]]
id = "com.base.properties.maximumDefense"
type = "int32"

[[property]]
id = "com.base.properties.requiredStrength"
type = "int32"

[[property]]
id = "com.base.properties.requiredDexterity"
type = "int32"

[[property]]
id = "com.base.properties.requiredLevel"
type = "int32"

[[property]]
id = "com.base.properties.requiredLevel"
type = "int32"

[[property]]
id = "com.base.properties.requiredClass"
type = "int32"