[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.100"
async-trait = "0.1.89"
thiserror = "2.0.17"
serde_json = "1.0.145"
sled = "0.34.7"
tokio = {version = "1.48.0", features = ["full"]}
